# Generated by Django 5.1.7 on 2025-06-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_feature_db', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='category',
            new_name='country_name',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='top_keys',
        ),
        migrations.AddField(
            model_name='feature',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feature',
            name='latest_report_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='sentiment_avg',
            field=models.FloatField(default=0.0),
        ),
    ]
