# Generated by Django 5.1.7 on 2025-06-15 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_feature_db', '0002_rename_category_feature_country_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='count',
            new_name='report_count',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='sentiment_avg',
        ),
        migrations.AddField(
            model_name='feature',
            name='avg_sentiment',
            field=models.FloatField(default=0.5),
        ),
        migrations.AlterField(
            model_name='feature',
            name='latest_report_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
