# Generated by Django 5.1.7 on 2025-06-15 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_feature_db', '0003_rename_count_feature_report_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='top_keywords_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
