# Generated by Django 5.1.7 on 2025-06-15 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_feature_db', '0004_feature_top_keywords_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='avg_sentiment',
        ),
        migrations.AddField(
            model_name='feature',
            name='sentiment_distribution_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
