# Generated by Django 5.1.7 on 2025-06-15 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_feature_db', '0005_remove_feature_avg_sentiment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='report_count',
        ),
        migrations.AddField(
            model_name='feature',
            name='report_trend_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
